import Link from "next/link";
import { ArrowRight, BrainCircuit, CheckCircle2, Code2, Compass, ShieldCheck, Sparkles, Target } from "lucide-react";

const features = [
  { icon: ShieldCheck, title: "Proof, not promises", text: "Bring together projects, credentials, assessments, and real work in one trusted profile." },
  { icon: Target, title: "See your next move", text: "Understand where you are strong, what is missing, and which role fits you best." },
  { icon: Compass, title: "Learn with direction", text: "Turn skill gaps into a focused roadmap with practical tasks that build momentum." },
];
const skillBars = [["React & Next.js", "94%", "#6366f1"], ["Python / FastAPI", "89%", "#8b5cf6"], ["Cloud & DevOps", "76%", "#22d3ee"]] as const;

export default function LandingPage() {
  return <main style={{ minHeight: "100vh", background: "#ffffff", color: "#172033", overflow: "hidden" }}>
    <div style={{ position: "absolute", top: -180, left: "38%", width: 540, height: 540, borderRadius: "50%", background: "radial-gradient(circle, rgba(99,102,241,.16), rgba(139,92,246,.06) 45%, transparent 70%)", pointerEvents: "none" }} />
    <header style={{ position: "relative", zIndex: 1, maxWidth: 1180, margin: "0 auto", padding: "22px 28px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20 }}>
      <Link href="/" aria-label="SkillPassport home" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none", color: "#172033" }}><span style={{ width: 38, height: 38, borderRadius: 12, background: "linear-gradient(135deg, #6366f1, #8b5cf6)", display: "grid", placeItems: "center", boxShadow: "0 8px 18px rgba(99,102,241,.24)" }}><Sparkles size={19} color="white" /></span><span style={{ fontSize: 20, fontWeight: 800, letterSpacing: "-.04em" }}>Skill<span style={{ color: "#6366f1" }}>Passport</span></span></Link>
      <nav style={{ display: "flex", alignItems: "center", gap: 10 }}><Link href="/login" style={{ color: "#4b5568", fontWeight: 650, fontSize: 14, textDecoration: "none", padding: "10px 14px" }}>Sign in</Link><Link href="/register" style={{ color: "white", background: "#4f46e5", borderRadius: 10, fontWeight: 700, fontSize: 14, textDecoration: "none", padding: "11px 17px", boxShadow: "0 6px 16px rgba(79,70,229,.24)" }}>Create account</Link></nav>
    </header>
    <section className="home-hero" style={{ position: "relative", zIndex: 1, maxWidth: 1180, margin: "0 auto", padding: "78px 28px 90px", display: "grid", gridTemplateColumns: "minmax(0, 1.05fr) minmax(360px, .95fr)", alignItems: "center", gap: 64 }}>
      <div><div style={{ display: "inline-flex", alignItems: "center", gap: 8, color: "#4338ca", background: "#eef2ff", border: "1px solid #dbe4ff", borderRadius: 999, padding: "7px 12px", fontSize: 13, fontWeight: 700 }}><Sparkles size={14} /> Your evidence-backed career profile</div><h1 style={{ fontSize: "clamp(44px, 5.5vw, 70px)", lineHeight: 1.03, letterSpacing: "-.065em", margin: "22px 0", fontWeight: 850 }}>Make your skills<br /><span style={{ color: "#4f46e5" }}>impossible to miss.</span></h1><p style={{ maxWidth: 570, fontSize: 18, lineHeight: 1.65, color: "#5f6879", margin: "0 0 32px" }}>SkillPassport turns the work you have done into a clear, shareable profile—so recruiters and teams can see what you can actually build.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}><Link href="/register" style={{ display: "inline-flex", alignItems: "center", gap: 9, background: "linear-gradient(135deg, #4f46e5, #7c3aed)", color: "white", padding: "15px 20px", borderRadius: 12, fontSize: 15, fontWeight: 750, textDecoration: "none", boxShadow: "0 12px 24px rgba(79,70,229,.25)" }}>Build your passport <ArrowRight size={18} /></Link><Link href="/passport/alex-chen" style={{ display: "inline-flex", alignItems: "center", gap: 8, border: "1px solid #d9deea", color: "#34405a", padding: "14px 19px", borderRadius: 12, fontSize: 15, fontWeight: 700, textDecoration: "none", background: "white" }}>View an example</Link></div><div style={{ display: "flex", flexWrap: "wrap", gap: 18, marginTop: 25, color: "#667085", fontSize: 13, fontWeight: 600 }}><span style={{ display: "flex", gap: 6, alignItems: "center" }}><CheckCircle2 size={15} color="#10b981" /> Free to get started</span><span style={{ display: "flex", gap: 6, alignItems: "center" }}><CheckCircle2 size={15} color="#10b981" /> Built around your real work</span></div></div>
      <div style={{ position: "relative", padding: 10 }}><div style={{ position: "absolute", inset: 20, borderRadius: 28, background: "linear-gradient(135deg, rgba(99,102,241,.18), rgba(34,211,238,.13))", filter: "blur(25px)" }} /><div style={{ position: "relative", background: "white", border: "1px solid #e3e7f0", borderRadius: 22, boxShadow: "0 24px 60px rgba(37,47,74,.14)", overflow: "hidden" }}><div style={{ padding: "18px 20px", borderBottom: "1px solid #edf0f5", display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ display: "flex", gap: 6 }}><i style={{ width: 8, height: 8, borderRadius: "50%", background: "#fca5a5" }} /><i style={{ width: 8, height: 8, borderRadius: "50%", background: "#fcd34d" }} /><i style={{ width: 8, height: 8, borderRadius: "50%", background: "#6ee7b7" }} /></div><span style={{ color: "#667085", fontSize: 12, fontWeight: 650 }}>Your Skill Passport</span></div><div style={{ padding: 24 }}><div style={{ display: "flex", alignItems: "center", gap: 13, marginBottom: 26 }}><div style={{ width: 48, height: 48, borderRadius: 15, background: "linear-gradient(135deg, #ddd6fe, #cffafe)", display: "grid", placeItems: "center", color: "#4f46e5", fontWeight: 800 }}>AC</div><div><strong style={{ display: "block", fontSize: 16 }}>Alex Chen</strong><span style={{ color: "#667085", fontSize: 13 }}>Full-stack developer</span></div><span style={{ marginLeft: "auto", color: "#047857", background: "#ecfdf5", padding: "5px 8px", borderRadius: 99, fontSize: 11, fontWeight: 750 }}>Verified</span></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 22 }}><div style={{ padding: 13, borderRadius: 12, background: "#f5f3ff" }}><span style={{ color: "#6d5bd0", fontSize: 12, fontWeight: 700 }}>PROFILE SCORE</span><strong style={{ display: "block", color: "#312e81", fontSize: 25, marginTop: 4 }}>94%</strong></div><div style={{ padding: 13, borderRadius: 12, background: "#ecfeff" }}><span style={{ color: "#0e7490", fontSize: 12, fontWeight: 700 }}>EVIDENCE</span><strong style={{ display: "block", color: "#155e75", fontSize: 25, marginTop: 4 }}>18</strong></div></div><div style={{ fontSize: 13, fontWeight: 750, marginBottom: 14 }}>Verified skill strengths</div>{skillBars.map(([name, score, color]) => <div key={name} style={{ marginBottom: 14 }}><div style={{ display: "flex", justifyContent: "space-between", color: "#475467", fontSize: 12, marginBottom: 6 }}><span>{name}</span><strong>{score}</strong></div><div style={{ height: 7, borderRadius: 99, background: "#edf0f7" }}><div style={{ height: "100%", width: score, borderRadius: 99, background: color }} /></div></div>)}</div></div></div>
    </section>
    <section style={{ borderTop: "1px solid #edf0f5", borderBottom: "1px solid #edf0f5", background: "#fbfcff" }}><div style={{ maxWidth: 1180, margin: "0 auto", padding: "68px 28px", textAlign: "center" }}><p style={{ color: "#6366f1", fontWeight: 750, fontSize: 13, textTransform: "uppercase", letterSpacing: ".11em", margin: 0 }}>A profile with substance</p><h2 style={{ fontSize: "clamp(30px, 4vw, 44px)", letterSpacing: "-.045em", margin: "12px 0 42px" }}>Everything you need to show your progress.</h2><div className="home-features" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 20, textAlign: "left" }}>{features.map(({ icon: Icon, title, text }) => <article key={title} style={{ background: "white", border: "1px solid #e7eaf1", borderRadius: 16, padding: 25 }}><span style={{ width: 42, height: 42, borderRadius: 12, display: "grid", placeItems: "center", background: "#eef2ff", color: "#4f46e5" }}><Icon size={21} /></span><h3 style={{ fontSize: 18, margin: "18px 0 8px", letterSpacing: "-.025em" }}>{title}</h3><p style={{ color: "#667085", fontSize: 14, lineHeight: 1.6, margin: 0 }}>{text}</p></article>)}</div></div></section>
    <section style={{ maxWidth: 1050, margin: "0 auto", padding: "82px 28px", textAlign: "center" }}><div style={{ borderRadius: 24, color: "white", padding: "clamp(36px, 7vw, 70px) 26px", background: "linear-gradient(120deg, #312e81, #4f46e5 55%, #0891b2)", boxShadow: "0 20px 45px rgba(79,70,229,.25)" }}><BrainCircuit size={30} style={{ marginBottom: 12 }} /><h2 style={{ fontSize: "clamp(30px, 4vw, 44px)", letterSpacing: "-.05em", margin: "0 0 13px" }}>Your next opportunity starts with proof.</h2><p style={{ maxWidth: 570, margin: "0 auto 25px", color: "#e0e7ff", lineHeight: 1.6 }}>Create an account, add the work you are proud of, and share a profile that speaks for itself.</p><Link href="/register" style={{ display: "inline-flex", alignItems: "center", gap: 8, background: "white", color: "#4338ca", padding: "13px 18px", fontWeight: 800, borderRadius: 10, textDecoration: "none" }}>Create your account <ArrowRight size={17} /></Link></div></section>
    <footer style={{ borderTop: "1px solid #edf0f5", padding: "25px 28px", color: "#667085", fontSize: 13 }}><div style={{ maxWidth: 1180, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, flexWrap: "wrap" }}><span>© 2026 SkillPassport</span><span style={{ display: "flex", alignItems: "center", gap: 7 }}><Code2 size={15} /> Built for people who keep learning.</span></div></footer>
    <style>{`@media (max-width: 800px) { .home-hero { grid-template-columns: 1fr !important; padding-top: 48px !important; gap: 40px !important; } .home-features { grid-template-columns: 1fr !important; } }`}</style>
  </main>;
}
